### ISSUE TITLE
SCHEMA: Proposals to standardize schema/objects/*.yaml formats

### ISSUE THREAD

**Issue by rwblair** [bids-standard/bids-specification#1088]
From conversations in #1086 the key values and name fields are not used entirely consistently in the schema objects. 
columns.yaml uses the `name` field value as the actual header column name we look for in tsv headers.
entities.yaml uses the `entity` field value as the literal entity that we look for in file names
suffixes.yaml uses the entries key as the literal suffix that we look for in file names.

Except for columns.yaml `name` is used as pretty printable/user friendly display name for the object. 

The key used for an object is always how we refer to an object within the specification.

suffix and columns should have the values that we look for in datasets moved from their respective places into a new field.

Proposal 1 is to follow entity suite and have a special key-name unique to that object type. So from columns.yaml this:
```yaml
acq_time__scans:
  name: acq_time
  description: |
    Acquisition time refers to when the first data point in each run was acquired.
```
Becomes:
```yaml
acq_time__scans:
  name: Acquisition Time
  column: acq_time
  description: |
    Acquisition time refers to when the first data point in each run was acquired.
```

Proposal 2 would be to standardize on a single key name across object to represent in dataset values. If we followed columns suite and used `name` for this, pretty print values could shift to `display_name`:
```yaml
# suffix
TwoPE:  # some unambiguous reference that works for MATLAB and ancpBIDS
  name: 2PE  # The actual value used in the specification
  display_name: 2-photon excitation microscopy  # The pretty name
  description: |
    2-photon excitation microscopy imaging data

# entity
inversion:  # also used for variable names in pybids
  name: inv
  display_name: Inversion Time
  description: |
    If files belonging to an entity-linked file collection are acquired at different
    inversion times, the `_inv-<index>` key/value pair MUST be used to distinguish
    individual files.
    This entity represents the `"InversionTime` metadata field. Please note that the `<index>`
    denotes the number/index (in the form of a nonnegative integer), not the `"InversionTime"`
    value which needs to be stored in the field `"InversionTime"` of the separate JSON file.
  type: string
  format: index

# column
type__electrodes:
  name: type
  display_name: Electrode Type
  description: |
    Type of the electrode (for example, cup, ring, clip-on, wire, needle).
  type: string
```

Instead of `name` there may be some other more appropriate key name to use, some floated during the 21.04.2022 schema meeting were `alias`, `value`, `shorthand`, etc but none felt quite right.

I would like to solicit input on the proposals and other potential solutions.

**Comment by rwblair** [comment]
@bids-standard/schema-users

**Comment by tsalo** [comment]
Also want to throw in an extension example:

```YAML
any:
  name: ".*"
  display_name: Any Extension
  description: |
    Any extension is allowed

none:
  name: ""
  display_name: No Extension
  description: |
    A file with no extension.
```

```YAML
- suffixes:
  - headshape
  extensions:
  - any
  - none
  entities:
    subject: required
    session: optional
    acquisition: optional
```

**Comment by effigies** [comment]
I think there was one additional proposal, which is to distinguish datatype, suffix and extension as special kinds, having a "value" rather than a name:

```YAML
# Suffix
TwoPE:  # some unambiguous reference that works for MATLAB and ancpBIDS
  value: 2PE  # The actual value used in the specification
  display_name: 2-photon excitation microscopy  # The pretty name
  description: |
    2-photon excitation microscopy imaging data

# Datatype
anatomical:
  value: anat
  display_name: Anatomical Magnetic Resonance Imaging
  description: |
    Magnetic resonance imaging sequences designed to characterize static, anatomical features.

# Extension
bdf:
  value: ".bdf"
  display_name: Biosemi Data Format
  description: |
    A [Biosemi](https://www.biosemi.com/) Data Format file.

    Each recording consists of a single `.bdf` file.
    [`bdf+`](https://www.teuniz.net/edfbrowser/bdfplus%20format%20description.html) files are permitted.
    The capital `.BDF` extension MUST NOT be used.
```

Meanwhile entities, columns and metadata could follow the convention 2:

```YAML
# entity
inversion:  # also used for variable names in pybids
  name: inv
  display_name: Inversion Time
  description: |
    If files belonging to an entity-linked file collection are acquired at different
    inversion times, the `_inv-<index>` key/value pair MUST be used to distinguish
    individual files.
    This entity represents the `"InversionTime` metadata field. Please note that the `<index>`
    denotes the number/index (in the form of a nonnegative integer), not the `"InversionTime"`
    value which needs to be stored in the field `"InversionTime"` of the separate JSON file.
  type: string
  format: index

# column
type__electrodes:
  name: type
  display_name: Electrode Type
  description: |
    Type of the electrode (for example, cup, ring, clip-on, wire, needle).
  type: string

# Metadata
AcquisitionDuration:
  name: AcquisitionDuration
  display_name: AcquisitionDuration
  description: |
    Duration (in seconds) of volume acquisition.
    Corresponds to DICOM Tag 0018, 9073 `Acquisition Duration`.
    This field is mutually exclusive with `"RepetitionTime"`.
  type: number
  exclusiveMinimum: 0
  unit: s
```

That said, metadata is also a bit of its own thing as well, since they are all valid identifiers and we never reference them except as literals in the spec, `"<key>" == <key>.name == <key>.display_name`. So maybe we should not try to uniformize it in this process.
