### ISSUE TITLE
Formalize participants' age to actually allow for other than year units/durations 

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1633]
ATM it must be in years (according to schema and hardcoded there assumptions), although [text](https://github.com/bids-standard/bids-specification/blob/0dcb141fccec5bbd92e482a071fefba0d0bbfdb1/src/modality-agnostic-files.md?plain=1#L263) suggests differently 

```
If no `units` is provided for age, it will be assumed to be in years relative to date of birth.
```

which was suggested/accepted in code review of #459 but 1. no alternative units are specified (thus unknown/useless) ; 2. such relaxation was not **later** reflected in the schema which now just [hardcode](https://github.com/bids-standard/bids-specification/blob/HEAD/src/schema/objects/columns.yaml#L35) via `unit: years` without alternative unit values provided. (not even sure if we formalize units to be machine readable ATM, e.g. see #1631 to fix some values)

@bids-standard/bep032  is working on  animal ecephys. In "animal world" restriction to age in years is often too restrictive, ambiguous in conversion (# of days in a year changes, # of days in month variable, etc) or not even expressive enough (pre-gestational age etc; let's keep that for a separate issue).  So we need to improve on specification of age by allowing other "units" and also allow for metadata field following some dictionary which would allow specification of the "age reference".  Here is what is done in other standards/uses:

-  NWB uses "age" of "text" type . For DANDI then it allows for treating  [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations) values if those are specified, enforced during metadata validation using [nwbinspector](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/nwbfile_metadata.py#L133) . Use of ISO 8601 makes any duration inambigous.

Since we are "unit" oriented ATM, I think the easiest resolution for this aspect would be to just do implement in the schema on what is promised in the text:

- Consider "Units" sidecar file value
- Define explicit "unit" values which would be accepted for age: year, month, day, hour, minute, s, ms

Question to schema folks (@effigies @rwblair @nellh): how difficult would be to generalize current check

```yaml
CheckAge89:
  issue:
    code: AGE_89
    message: .... trimmed...
    level: warning
  selectors:
    - path == 'participants.tsv'
    - columns.age != null
  checks:
    - max(columns.age) < 89
```

to support use of the "Units" in the side car?

**Comment by Remi-Gau** [comment]
Sort of related: 
- https://github.com/bids-standard/bids-specification/issues/1020
- https://github.com/bids-standard/bids-specification/issues/458

**Comment by yarikoptic** [comment]
![image](https://github.com/bids-standard/bids-specification/assets/39889/ea4f3251-8d7b-4ccf-8f82-d00ce18a1ad9)

**Comment by yarikoptic** [comment]
https://giphy.com/gifs/bushes-spicer-correction-COYGe9rZvfiaQ/fullscreen

**Comment by yarikoptic** [comment]
@effigies @rwblair we need to get back to this -- it is crucial for animal research.

My original

- https://github.com/bids-standard/bids-specification/pull/1791

was closed by @rwblair and it was partially addressed (89+ aspect) in

- https://github.com/bids-standard/bids-specification/pull/2162

but overall now we still have it ["hardcoded" as JSON schema record](https://github.com/bids-standard/bids-specification/blob/master/src/schema/objects/columns.yaml#L35)

```yaml
age:
  name: age
  display_name: Subject age
  description: |
    Numeric value in years (float or integer value).

    For privacy purposes, participant ages should be capped at 89.
    Using "89+" for ages above 88 is DEPRECATED.
  definition: {
    "LongName": "Subject age",
    "Description": "Subject age in postnatal years",
    "Format": "number",
    "Units": "year",
    "Maximum": 89,
  }
```

from that read, and IIRC

- this is still hardcoded to "years" in description
- we cannot override in the `participants.json` to be different (what specific values?) unit

Is my observation is correct and we still need to work out a solution or we can overload and thus this issue could be closed???
