### ISSUE TITLE
Add support for relating to DICOM fields directly in the schema

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1759]
Inspired by 
- https://github.com/bids-standard/bids-specification/pull/1450#issuecomment-2028576595

ATM we have not schematized the relationships we might have between our metadata fields and (meta)data from DICOMS. We express it in free word form and that is why we lack consistency (hence #1450 and fresh #1758).  I think, with possible future extensions in mind, we should add to schema for metadata fields

```
relations:
   dicom:
      {relation}:
         - TAG
```

e.g.
```
relations:
  dicom:
    identicalTo:
      - 0002, 0003
      - 0002, 0008
```
or
```
relations:
  dicom:
    derivedFrom:
      - 0002, 0003
      - 0002, 0008
```

where 
- those relations are part of https://support.datacite.org/docs/connecting-to-works#summary-of-all-relationtypes without `is`
- can't have both `identicalTo` and `derivedFrom` (until we run into use case).

This would
- allow for consistent rendering and annotation of relations
- allow to hyperlink to DICOM standard description for those fields
- avoid necessity for verbal description in common principles such as proposed in https://github.com/bids-standard/bids-specification/pull/1450#issuecomment-2028576595
- make it generic, possibly opening possibility to relate to  nidm terms (attn @dbkeator , #423)
- allow for verification of validity of values by the "schema validator (tests)"
