### ISSUE TITLE
BIDS Schema: There should be a rule that encodes that multiple README files (with different extensions) are NOT allowed

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-specification#1951]
See title. Currently, the schema based BIDS-validator does not throw an error when this happens.

Steps to reproduce:

1. take a valid BIDS dataset with a README file
2. copy the README and add a different, valid, extension
3. validate
4. --> no error for duplicate README is thrown

source: https://bids-specification.readthedocs.io/en/stable/glossary.html#readme-files

> A BIDS dataset MUST NOT contain more than one README file (with or without extension) at its root directory.

NOTE that the legacy validator does throw an error:

Error 2: [Code 228] MULTIPLE_README_FILES

- xref: https://github.com/mne-tools/mne-bids/pull/1318

**Comment by effigies** [comment]
I think we were waiting on https://github.com/bids-standard/bids-specification/pull/1492 to settle how the schema represents it, but we could rewrite the existing one-offs for now. e.g.,

```yaml
DuplicateReadmes:
  issues:
    code: MULTIPLE_README_FILES
    message: ...
    level: error
  selectors:
    - match(path, '^/README.*')
  checks:
    - exists(["README", "README.md", "README.rst", "README.txt"], "dataset") == 1
```
