### ISSUE TITLE
Allow for GeneratedBy in any sidecar .json file to collect their provenance

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#1970]
### Your idea

- https://github.com/bids-standard/bids-2-devel/issues/80#issuecomment-2437597659

and reflecting on
- https://github.com/bids-standard/bids-specification/pull/440

for GeneratedBy to be universally adopted at the Dataset level.

To accommodate provenance "per file", e.g. for dcm2niix and alike, we better allow for GeneratedBy at individual file level.

**Comment by effigies** [comment]
Not to speak for dcm2niix developers, but I am skeptical that a request to replace two JSON keys encoding `(name, version)` with a provenance sidecar will be well received. The complexity increase seems difficult to justify in a do-one-thing-correctly tool.

I think of prov as the domain of wrappers. Heudiconv could implement the proposal in this PR without any cooperation from dcm2niix.

It could also upgrade dcm2niix's fields to BIDS-prov, and skip over this step altogether.

**Comment by satra** [comment]
one option is to add the provenance keys to any sidecar json as an option.

**Comment by effigies** [comment]
@satra Could you elaborate how, for example, https://github.com/OpenNeuroDatasets/ds000224/blob/master/task-rest_bold.json would be changed to use the provenance keys?

**Comment by yarikoptic** [comment]
What provenance keys exactly @satra and @effigies?  In the scope of this issue I would see that file instead of 

```
	"ConversionSoftware": "dcm2niix",
	"ConversionSoftwareVersion": "v1.0.20170411 GCC4.4.7",
```

having

```
     "GeneratedBy": [
          {
             "name": "dcm2niix",
             "version": "v1.0.20170411 GCC4.4.7",
             "message": "Conversion from DICOM"
          }
     ]
```
or alike

**Comment by yarikoptic** [comment]
> [@cmaumet](https://github.com/cmaumet) [@satra](https://github.com/satra) isn't that falling under the scope of the provenance BEP?

Provenance BEP is formalizing specification of `.prov.jsonld`.  I am talking about expanding the use of **already formalized in BIDS** metadata field.

Similarly to adoption of `_desc` as an "easier quick way to describe provenance" and already having "GeneratedBy" side-car file we indeed in part would duplicate formalization in [BEP028: Provenance](https://bids.neuroimaging.io/bep028) which has much "wider" scope and an unknown ETA, but it could have a chance to take advantage of already existing in BIDS formalizations to produce minimal `.prov.jsonld` from those `GeneratedBy` fields if we adopt them.

**Comment by yarikoptic** [comment]
> Heudiconv could implement the proposal in this PR without any cooperation from dcm2niix.
> 
> It could also upgrade dcm2niix's fields to BIDS-prov, and skip over this step altogether.

a neat idea, I like it!  We would just need to merge BIDS-prov first. But also the question here was triggered by `dcm2niix` good desire to produce "BIDS standard" metadata fields to start with.

**Comment by satra** [comment]
we wanted to separate it into a different file simply for simplification that a tool could write out provenance without worrying about the bids json spec for an entity. this issue itself is bringing these two streams together.

there is currently a semantic conflict between the `generatedBy` keyword in bids spec versus bids prov. the prov keyword maps to an activity with potentially multiple agents (software or humans) being part of that activity. whereas the bids keyword maps directly to software agents that produced it. the simplification is fine, but it does mean the semantics of the keys are different, contextualized by specs, and will be in conflict with each other when brought together from a machine understanding perspective.

for keywords that could be brought in from prov, please see the `Alternative representation for file-level provenance JSON-LD` section of the [BEP28 document](https://bids.neuroimaging.io/bep028). we did consider that eventually such a set of keys could be added to the json, which describes information about the blob to which it is connected in the first place.

**Comment by yarikoptic** [comment]
> the simplification is fine, but it does mean the semantics of the keys are different, contextualized by specs, and will be in conflict with each other when brought together from a machine understanding perspective.

since we already have generatedBy formalized in BIDS, if we decide to rename or change format, we would need to slate it for BIDS 2.0 or whatever other major release to come and automate that change in migration/upgrade script.  I initiated

- https://github.com/bids-standard/bids-2-devel/issues/89

so please chime in on that aspect there.

This issue is largely orthogonal from that discussion and just expands adoption of already formalized in BIDS `generatedBy`.

**Comment by yarikoptic** [comment]
@effigies WDYT about the example I have provided [above](https://github.com/bids-standard/bids-specification/issues/1970#issuecomment-2438757531)?  I have improved it slightly now.

- I maintain my opinion that it would be great to formalize GeneratedBy to the file level metadata
  - question: I failed to identify file in the schema where we would define common sidecar JSON fields . Do we even have any so far?
- This could be a nice reason to extract/formalize ["migrate" functionality](https://github.com/bids-standard/bids-specification/pull/1775/files#diff-24b8a97543a1dc43190b8d5b070df26e1b88023f2b468b4483255af049788788R39) from #1775 and make it easy for users to convert already present fields into this new standardized form from earlier versions.

**Comment by yarikoptic** [comment]
I agree that it would be **great** to see BIDS-Prov BEP finalized an a proper PROV records appear in BIDS. Also examples would be great -- in particular the one for above information on `DICOM -> nii.gz` conversion.

But I want to reiterate that regardless of the destiny of BIDS-Prov and its records, I am talking about already existing/formalized `GeneratedBy`.  When BIDS-Prov is accepted we would ideally need to move/transform existing GeneratedBy into BIDS-Prov.  But regardless of that -- meanwhile, we keep getting BIDS datasets proliferated with a completely ad-hoc and non-formalized fields.  This issue is an effort to formalize them at least to the form already present in the standard. That could be done pretty rapidly.  Seeing a totally **new** formalization accepted to the standard would take much longer IMHO, and thus make even more datasets proliferated with non-standardized metadata.

**Comment by effigies** [comment]
So Yarik's example would become:

```yaml
"GeneratedBy": {
  "Id": "urn:conversion-<nonce>",
  "Type": "Activity",
  "Label": "Conversion",
  "Used": "bids:sourcedata:somefile.dcm",
  "AssociatedWith": {
    "Id": "urn:dcm2niix-<nonce>",
    "Type": "Software",
    "Label": "dcm2niix",
    "Version": "v1.0.20170411 GCC4.4.7"
  }
}
```

Is "Used" required? That may be problematic if filenames are not anonymized. Is "Id" required? If so, guidance on how to generate the nonce would probably be required for users to accept it. And I suppose if Heudiconv does some kind of additional adjustment, it would look like:

```yaml
"GeneratedBy": {
  "Id": "urn:curation-<nonce>",
  "Type": "Activity",
  "Label": "Curation",
  "Used": {
    "Id": "urn:converted-tmp-file-<nonce>",
    "GeneratedBy": {
      "Id": "urn:conversion-<nonce>",
      "Type": "Activity",
      "Label": "Conversion",
      "Used": "bids:sourcedata:somefile.dcm",
      "AssociatedWith": {
        "Id": "urn:dcm2niix-<nonce>",
        "Type": "Software",
        "Label": "dcm2niix",
        "Version": "v1.0.20170411 GCC4.4.7"
      }
    }
  },
  "AssociatedWith": {
    "Id": "urn:heudiconv-<nonce>",
    "Type": "Software",
    "Label": "heudiconv",
    "Version": "1.3.2"
  }
}
```

If we were able to forego Id and Used:

```yaml

"GeneratedBy": {
  "Type": "Activity",
  "Label": "Curation",
  "Used": {
    "GeneratedBy": {
      "Type": "Activity",
      "Label": "Conversion",
      "AssociatedWith": {
        "Type": "Software",
        "Label": "dcm2niix",
        "Version": "v1.0.20170411 GCC4.4.7"
      }
    }
  },
  "AssociatedWith": {
    "Type": "Software",
    "Label": "heudiconv",
    "Version": "1.3.2"
  }
}
```

@yarikoptic:

> But I want to reiterate that regardless of the destiny of BIDS-Prov and its records, I am talking about already existing/formalized `GeneratedBy`. When BIDS-Prov is accepted we would ideally need to move/transform existing GeneratedBy into BIDS-Prov. But regardless of that -- meanwhile, we keep getting BIDS datasets proliferated with a completely ad-hoc and non-formalized fields. This issue is an effort to formalize them at least to the form already present in the standard. That could be done pretty rapidly. Seeing a totally **new** formalization accepted to the standard would take much longer IMHO, and thus make even more datasets proliferated with non-standardized metadata.

A couple responses:

1) I would rather not proliferate standards we intend to deprecate. If we know BIDS-prov is coming down the pipeline, it seems counterproductive to me to standardize on something else. Nothing is stopping Heudiconv from adopting `GeneratedBy` as a convention, as nonstandard metadata is always permitted.
2) Why not use BIDS-prov? Has it been changing? My impression was that it's more-or-less done.
