### ISSUE TITLE
RULE change that makes about 50% of OpenNeuro EEG datasets invalid

### ISSUE THREAD

**Issue by arnodelorme** [bids-standard/bids-specification#2042]
A rule (new or old?), enforced in the latest BIDS validator version, forces "_coordsystem" and "_electrodes" to not have a task associated with them, makes 50% of the OpenNeuro EEG datasets invalid (that's more than 100 EEG datasets conservatively). This is because most of the OpenNeuro EEG datasets are exported with our EEG-BIDS tool https://github.com/sccn/EEG-BIDS, which automatically adds the task name to "_coordsystem" and "_electrodes" files (which was acceptable before the recent change to the rules and/or BIDS validator).

[ERROR] ENTITY_NOT_IN_RULE Entity not listed as required or optional for files with this suffix
/sub-021/ses-pre/eeg/sub-021_ses-pre_task-SART_coordsystem.json - task not in rule rules.files.raw.channels.coordsystem__eeg

[ERROR] ENTITY_NOT_IN_RULE Entity not listed as required or optional for files with this suffix
/sub-021/ses-pre/eeg/sub-021_ses-pre_task-SART_electrodes.tsv - task not in rule rules.files.raw.channels.electrodes

I suggest undoing the change, which primarily creates issues with backward compatibility, unless there is a deep-rooted reason for it (but what about "_channels" files, for example? Why should "_electrodes.tsv" files be treated differently than "_channels.tsv" files?).

@neuromechanist and @robertoostenveld , please comment as needed.

**Comment by neuromechanist** [comment]
AFAIK, the [EEG-BIDS specifications](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/electroencephalography.html#:~:text=*_electrodes.tsv%20files%20SHOULD,to%20indicate%20this.) only recommend NOT using the `task` entity for `electrodes.tsv` and `coordsystem.json`:
> *_electrodes.tsv files SHOULD NOT be duplicated for each data file, for example, during multiple runs of a task. The [inheritance principle](https://bids-specification.readthedocs.io/en/stable/common-principles.html#the-inheritance-principle) MUST be used to find the appropriate electrode positions for a given data file. If electrodes are repositioned, it is RECOMMENDED to use multiple sessions to indicate this.

I believe the MUST term there is to use inheritance when the `task` entity is not used, and SHOULD NOT is the term that must be used for enforcing the use of the `task` entity for electrodes.tsv` and `coordsystem.json`.

**Comment by neuromechanist** [comment]
On second look, this seems to be a genuine bug, because both files have `task` as optional:

```yaml
electrodes:
  suffixes:
    - electrodes
  extensions:
    - .json
    - .tsv
  datatypes:
    - eeg
    - ieeg
  entities:
    subject: required
    session: optional
    task: optional
    acquisition: optional
    run: optional
    space: optional

coordsystem:
  suffixes:
    - coordsystem
  extensions:
    - .json
  datatypes:
    - meg
    - nirs
  entities:
    subject: required
    session: optional
    task: optional
    acquisition: optional

# (i)EEG has a space entity
coordsystem__eeg:
  $ref: rules.files.raw.channels.coordsystem
  datatypes:
    - eeg
    - ieeg
  entities:
    $ref: rules.files.raw.channels.coordsystem.entities
    space: optional
```

There is a warning that should be issued via `rules.check.channels` that is appropriate.

cc: @effigies, would you mind having a look?
