### ISSUE TITLE
columns.yml: unclear difference in schema in defining within record or within "definition" sub-record

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#2045]
In https://github.com/bids-standard/bids-specification/blob/HEAD/src/schema/objects/columns.yaml we have 

```yaml
duration:
  name: duration
  display_name: Event duration
  description: |
    Duration of the event (measured from onset) in seconds.
    Must always be either zero or positive (or `n/a` if unavailable).
    A "duration" value of zero implies that the delta function or event is so
    short as to be effectively modeled as an impulse.
  type: number 
  unit: s
  minimum: 0
```

where there is `type` and `unit` within the record but then there is 

```yaml
age:
  name: age
  display_name: Subject age
  description: |
    Numeric value in years (float or integer value).
  
    It is recommended to tag participant ages that are 89 or higher as 89+,
    for privacy purposes.
  definition: {
    "LongName": "Subject age",
    "Description": "Subject age in postnatal years",
    "Units": "year",
  }
```

where there is `definition` field with `"Units"` in it.  I found no mentioning of `definition:` within https://github.com/bids-standard/bids-specification/tree/master/src/schema README.

- is such difference warranted or should we seek to unify by either abolishing `definition` and moving all into the record or unifying into everything having `definition`?
  - why `unit` vs `Units` difference? very loosely related https://github.com/bids-standard/bids-2-devel/issues/15  
  - and overall why in "definition" attributes are Capitalized?
- why `definition` is in JSON syntax (subclass of YAML, I know) and not regular YAML?

If not to be changed anyhow, should be addressed by clarifications within https://github.com/bids-standard/bids-specification/blob/master/src/schema/README.md .

**Comment by effigies** [comment]
https://github.com/bids-standard/bids-specification/pull/1838

**Comment by effigies** [comment]
I agree we should update the README, and that should have been part of that PR.

**Comment by effigies** [comment]
Reopening because this was *not* documented, even in the schema README, in #2162. For reference, in #2048 we had a detailed discussion and I will briefly recap the two kinds of column definitions at the bottom of this comment.

I want to revisit this discussion in light of #2400, which adds language to `objects.columns.age.description` to make clear that it is a default interpretation that can be overridden. I think that is a good improvement. It also adds that to the `objects.columns.age.definition.Description`, which I disagree with because `objects.columns.*.definition` were intended to be dictionaries that could be dropped as-is into a JSON sidecar without changing the meaning from the default, and including "default" language would be somewhat confusing to see in a sidecar.

So I have two suggestions:

1. I think we should change `definition` to `default_definition`, and this can be displayed in the glossary as a JSON snippet that can be copy-pasted.
2. We can use this opportunity (modifying schema structure) to add a `strict` keyword, making strictness (non-overridability) a first-class concept and document it on a per-column basis. I would like for an overridable column like `age` to look like:

```yaml
age:
  name: age
  display_name: Subject age
  strict: false
  description: |
    Numeric value (float or integer value).
    By default expressed using "year" as the unit. Other possible "Units" are described in
    [Units](SPEC_ROOT/common-principles.md#units).

    For privacy purposes, participant ages should be capped at 89 years.
    Using "89+" for ages above 88 is DEPRECATED.
  default_definition: {
    "LongName": "Subject age",
    "Description": "Subject postnatal age in years",
    "Format": "number",
    "Units": "year",
    "Maximum": 89,
  }
```

And a non-overridable column like optode type to be:

```yaml
type__optodes:
  name: type
  display_name: Type
  strict: true
  description: |
    The type of the optode.
  type: string
  enum:
    - source
    - detector
  default_definition: {
    "LongName": "Optode type",
    "Description": "Type of the optode",
    "Format": "string",
    "Levels": {
      "source": "A light emitting device, sometimes called a transmitter.",
      "detector": "A photoelectric transducer, sometimes called a receiver.",
    }
  }
```

Thus, even strict columns could have a `default_definition` you can copy-paste, and curation tools could insert them into JSON sidecars on behalf of users. By setting the `strict` flag, we can direct validators to require compatibility with the schema definition or permit an override, and tools can know whether they can source the definition from the BIDS schema or need to read and interpret a sidecar definition.

In addition to rendering JSON snippets in the glossary, the TSV column tables in the main spec should add a "This column may [not] be overridden." to each description.

And I would suggest making clear in common principles that overridable columns are 100% overridden, and any validation is based on the column definition, and lacking type information will result in no validation. We could make `"Format"` RECOMMENDED so that people get a warning that the column isn't being validated.

---

* "sidecar-defined" columns, which use the fields presented in common principles (e.g., `"Format"`, `"Levels"`). When they appear in the specification, they are as a JSON blob in a `definition` field. These can generally be overridden, since they were introduced as examples and were not intended to replace curators actually describing their data. "age", "sex" and "handedness" in `participants.tsv` are examples here.
* "schema-defined" columns, which use JSON-schema terms (e.g., `type`, `format`, `enum`). In general, these are not permitted to be overridden, and were strongly typed in the spec's plain language since introduction. `onset` in `events.tsv` or `type` in `channels.tsv` are examples here. Nonetheless, the validator permits adding definitions in JSON sidecars, so long as they do not conflict with the schema definition, to avoid penalizing curators who annotate their data.
