### ISSUE TITLE
What is the role of "tags" in schema's enum records

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/bids-specification#2059]
e.g at https://github.com/bids-standard/bids-specification/blob/fa2b5d85f7e0eb269c7c935819e29a616d39ab60/src/schema/objects/enums.yaml#L725 

```
GYRO:
  value: GYRO
  display_name: GYRO
  tags:
    - fnirs
    - motion
  description: |
    Gyrometer channel, one channel for each spatial axis.
    Column `component` for the axis MUST be added to the `*_channels.tsv` file (x, y, or z).
```

should it point to `modalities` or `datatypes` or `suffixes`? Present values seems to correspond to "ambiguous" modalities where `modality == datatype`

 Could it just be named accordingly (e.g. `modalities:`) instead of ambiguous `tags`?

attn @effigies
