### ISSUE TITLE
[BUG] Invalid schema (bad yaml file)

### ISSUE THREAD

**Issue by dipterix** [bids-standard/bids-specification#2060]
### Describe your problem in detail.

https://github.com/bids-standard/bids-specification/blob/fa2b5d85f7e0eb269c7c935819e29a616d39ab60/src/schema/objects/enums.yaml#L1139

YAML 1.1 interprets `y:...` as key `true` instead of literal `y`, hence this enum will be interpreted as

```json
{true: {
  value: true,
  display_name: true,
  ...
}}
```

### Describe what you expected.

Suggested change:

```yml
x:
  value: x
  display_name: x
  description: |
    The x dimension of the coordinate system.
"y":
  value: "y"
  display_name: "y"
  description: |
    The y dimension of the coordinate system.
z:
  value: z
  display_name: z
  description: |
    The z dimension of the coordinate system.
```

### BIDS specification section

https://bids-specification.readthedocs.io/en/latest/...
