### ISSUE TITLE
Convert entity table to machine-readable format

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#466]
I'm not sure if it's feasible, but it would be nice if the entity table was stored as a json file, in order to make it both programmatically accessible and centralized. I know that there is an equivalent file in [bids-validator](https://github.com/bids-standard/bids-validator/blob/6a937a1ba1d08d3e14d3f0c984ab6ba8a7f7a9fd/bids-validator/bids_validator/rules/file_level_rules.json) and [pybids](https://github.com/bids-standard/pybids/blob/5fab1dee770babffa7aef668b24cb59a90ba37ef/bids/layout/config/bids.json), but if the filename construction rules were centralized under the actual specification, then it would be much easier to update the specification across the ecosystem without having to update a range of other packages as well.

**Comment by jbteves** [comment]
I would like to second this as someone largely outside the ecosystem. I wanted to make a program which could generate filenames programmatically since we have a big, complicated study, but without a file like this it's hard to build tooling to that effect IMO.

**Comment by yarikoptic** [comment]
- I think `yaml` would be a better fit because could allow for comments and being friendlier to humans (cons: no de-factor validator, so should remain simple and probably for validation still use json schema validator)
- It could also allow for making data structure useful beyond entity table - e.g. with a listing of corresponding terms used for a given entity in a given modality (e.g. for this effort: https://github.com/bids-standard/bids-specification/issues/423)
- we could use it also in heudiconv to construct filenames following the standard order etc
- might be worth keeping such specifications in a separate lightweight repository which would then be either "linked" here via git submodules, or included via `git subtree` mechanism.  That would allow similar inclusion of it into repositories of the corresponding software projects
 - similar desire/related discussion happened recently in https://github.com/bids-standard/bids-specification/issues/423#issuecomment-623454571

**Comment by jbteves** [comment]
- As an outsider, `.json` is still preferable as more people are familiar with it and it is in line with many other choices in the specification, including the fact that metadata is stored in that same format.
- I think #423 is a good example of why approaches like this are useful, thanks for linking that.
- Using heudiconv in tandem with this would be *wonderful*
- I have no opinions on how it's stored, provided it can easily be fetched with a `git clone` or `curl` operation.

**Comment by tsalo** [comment]
What about something like the following? I've formatted it as yaml because that was easier to write freehand into a file, but could easily switch to json for the real thing. The suffices are organized into groups like the entity table to keep it reasonably short, but I could drop the groups and make each suffix a dictionary under the datatypes.

```
entities:
  sub:
    description: Subject
    format: label
  ses:
    description: Session
    format: label
  task:
    description: Task
    format: label
  acq:
    description: Acquisition
    format: label
  ce:
    description: Contrast Enhancing Agent
    format: label
  rec:
    description: Reconstruction
    format: label
  dir:
    description: Phase-Encoding Direction
    format: label
  run:
    description: Run
    format: index
  mod:
    description: Corresponding Modality
    format: label
  echo:
    description: Echo
    format: index
  recording:
    description: Recording
    format: label
  proc:
    description: Processed (on device)
    format: label
  space:
    description: Space
    format: label
datatypes:
  anat:
    group1:
      suffices:
        - T1w
        - T2w
        - T1rho
        - T1map
        - T2map
        - T2star
        - FLAIR
        - FLASH
        - PD
        - PDmap
        - PDT2
        - inplaneT1
        - inplaneT2
        - angio
      extensions:
        - nii.gz
        - nii
        - json
      entities:
        sub: required
        ses: optional
        acq: optional
        ce: optional
        rec: optional
    group2:
      suffices:
        - defacemask
      extensions:
        - nii.gz
        - nii
        - json
      entities:
        sub: required
        ses: optional
        acq: optional
        ce: optional
        rec: optional
        mod: optional
  func:
    group1:
      suffices:
        - bold
        - cbv
        - phase
        - sbref
      extensions:
        - nii.gz
        - nii
        - json
      entities:
        sub: required
        ses: optional
        task: required
        acq: optional
        ce: optional
        rec: optional
        dir: optional
        run: optional
        echo: optional
```

**Comment by yarikoptic** [comment]
@tsalo -- this looks beautiful to me!

@jbteves : I do agree that consistency which could be achieved by using .json is indeed a benefit. But IMHO YAML is so much nicer and human friendly that I simply can't resist it.  It also got a feature of XXI century -- support for `# comments`!

<details>
<summary>Here is a json view of the above yaml for comparison  -- although not too bad yet but as it grows I would find it more and more easy to orient in yaml than json and all the clutter from everything in "" really makes it less readable to me</summary> 

```yaml
{
  "entities": {
    "task": {
      "description": "Task", 
      "format": "label"
    }, 
    "ses": {
      "description": "Session", 
      "format": "label"
    }, 
    "sub": {
      "description": "Subject", 
      "format": "label"
    }, 
    "space": {
      "description": "Space", 
      "format": "label"
    }, 
    "ce": {
      "description": "Contrast Enhancing Agent", 
      "format": "label"
    }, 
    "echo": {
      "description": "Echo", 
      "format": "index"
    }, 
    "recording": {
      "description": "Recording", 
      "format": "label"
    }, 
    "acq": {
      "description": "Acquisition", 
      "format": "label"
    }, 
    "rec": {
      "description": "Reconstruction", 
      "format": "label"
    }, 
    "run": {
      "description": "Run", 
      "format": "index"
    }, 
    "proc": {
      "description": "Processed (on device)", 
      "format": "label"
    }, 
    "dir": {
      "description": "Phase-Encoding Direction", 
      "format": "label"
    }, 
    "mod": {
      "description": "Corresponding Modality", 
      "format": "label"
    }
  }, 
  "datatypes": {
    "anat": {
      "group1": {
        "suffices": [
          "T1w", 
          "T2w", 
          "T1rho", 
          "T1map", 
          "T2map", 
          "T2star", 
          "FLAIR", 
          "FLASH", 
          "PD", 
          "PDmap", 
          "PDT2", 
          "inplaneT1", 
          "inplaneT2", 
          "angio"
        ], 
        "extensions": [
          "nii.gz", 
          "nii", 
          "json"
        ], 
        "entities": {
          "rec": "optional", 
          "acq": "optional", 
          "ses": "optional", 
          "sub": "required", 
          "ce": "optional"
        }
      }, 
      "group2": {
        "suffices": [
          "defacemask"
        ], 
        "extensions": [
          "nii.gz", 
          "nii", 
          "json"
        ], 
        "entities": {
          "acq": "optional", 
          "ses": "optional", 
          "sub": "required", 
          "rec": "optional", 
          "ce": "optional", 
          "mod": "optional"
        }
      }
    }, 
    "func": {
      "group1": {
        "suffices": [
          "bold", 
          "cbv", 
          "phase", 
          "sbref"
        ], 
        "extensions": [
          "nii.gz", 
          "nii", 
          "json"
        ], 
        "entities": {
          "task": "required", 
          "ses": "optional", 
          "sub": "required", 
          "ce": "optional", 
          "echo": "optional", 
          "acq": "optional", 
          "rec": "optional", 
          "run": "optional", 
          "dir": "optional"
        }
      }
    }
  }
}

```
</details>
