### ISSUE TITLE
Rename modalities.yaml in schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#593]
The file [modalities.yaml](https://github.com/bids-standard/bids-specification/blob/5a7c1d75a92b4e1b4489a6cb01082720c268467f/src/schema/modalities.yaml) describes the technologies supported in the specification (e.g., MRI, EEG). Given that "modality" has its own meaning, and will soon have a distinct definition in **Common principles** (see #592), the naming of the file in the schema is misleading. Some viable alternatives might be "technologies.yaml" or "instruments.yaml".

**Comment by tsalo** [comment]
I'm leaning toward "instruments.yaml" after reading something @robertoostenveld wrote. Additionally, I like the idea of combining the EEG and iEEG data types (i.e., folders) under a shared instrument like "biopotential amplifiers" (again, per @robertoostenveld). What do folks think of this structure?

```yaml
---
mri:
  name: Magnetic Resonance Imaging
  datatypes:
    - anat
    - dwi
    - fmap
    - func
bioamp:
  name: Biopotential Amplification
  datatypes:
    - eeg
    - ieeg
meg:
  name: Magnetoencephalography
  datatypes:
    - meg
beh:
  name: Behavioral experiments
  datatypes:
    - beh
```

While this doesn't affect the specification at all at the moment, I think it would eventually impact the organization of the text. Currently, we have an MRI page with subsections for the different data types derived from the same instrument, while EEG and iEEG have separate pages. Ultimately, iEEG and EEG would also fall under one page (or major section) named "Biopotential Amplification".
