### ISSUE TITLE
[SCHEMA] MEG files not yet covered by the schema

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#810]
Trying to use the schema to index some things with bids-matlab, I came across some files that I think are not covered yet.

https://github.com/bids-standard/bids-examples/tree/master/ds000248/sub-01/meg

```
/bids-examples/ds000248/sub-01/meg
├── sub-01_acq-calibration_meg.dat   <---- HERE
├── sub-01_acq-crosstalk_meg.fif   <---- HERE
├── sub-01_coordsystem.json
├── sub-01_task-audiovisual_run-01_channels.tsv
├── sub-01_task-audiovisual_run-01_events.tsv
├── sub-01_task-audiovisual_run-01_meg.fif
└── sub-01_task-audiovisual_run-01_meg.json
```

They are mentioned in the appendix.

https://bids-specification.readthedocs.io/en/stable/99-appendices/06-meg-file-formats.html#cross-talk-and-fine-calibration-files

-  cross-talk file template: sub-<label>[_ses-<label>]_acq-crosstalk_meg.fif
-  fine-calibration file template: sub-<label>[_ses-<label>]_acq-calibration_meg.dat

The issue now though is that in the same folder we have files with the same suffix, same extention but different set of requirements for which entities are required. @tsalo is there a precedent about this?

**Comment by sappelhoff** [comment]
Good catch.

> Not perfect as it still leaves a blindspot for this:

We could perhaps "reserve" `calibration` and `crosstalk` for `acq`-labels, in that they can ONLY be used for actual crosstalk and cablibration files from the Neuromag/Elekta/Megin MEG format :thinking: 

but the two terms are fairly general and other people may (1) have already used them, or (2) want to use them in the future. I mean: There are lots of things to calibrate ... and crosstalk sounds like something that could be used in connectivity related research...

**Comment by Remi-Gau** [comment]
you read my mind!

**Comment by Remi-Gau** [comment]
I suspect that for the `.dat` we could have something like this:

```yml
# First group

- suffixes:
    - meg
  extensions:
    - /  # corresponds to BTi/4D data
    - .ds/
    - .json
    - .fif
    - .sqd
    - .con
    - .raw
    - .ave
    - .mrk
    - .kdf
    - .mhd
  entities:
    subject: required
    session: optional
    task: required
    acquisition: optional
    run: optional
    processing: optional
    split: optional

# Second group
- suffixes:
    - meg
  extensions:
    - .dat
  entities:
    acquisition: # note that this introduces in the schema the possibility to declare "reserved values"
      - requirement: required 
      - value: calibration
```

**Comment by Remi-Gau** [comment]
And then maybe for the `.fif` but this really changes the potential structure of the schema.

```yml
- suffixes:
    - meg
  extensions:
    - .fif
  entities:
    - option: 1
      subject: required
      session: optional
      task: required
      acquisition: optional
      run: optional
      processing: optional
      split: optional
    - option: 2
      subject: required
      acquisition: 
      - requirement: required 
      - value: crosstalk  
```

**Comment by tsalo** [comment]
Sorry for the massive delay in responding to this. @Remi-Gau I agree with your general idea, although I want to make sure it's as harmonious with the keywords (e.g., `anyOf`, `enum`) I took from the validator as possible.

Two initial thoughts:
1. We shouldn't need the "option" key. The dictionaries in your list are different, so that should be fine.
2. I think `type: string` + `enum: crosstalk` might fit better with our current structure than `value: crosstalk`.

**Comment by tsalo** [comment]
WDYT of this slightly adjusted version of your proposal?

```yaml
- suffixes:
    - meg
  extensions:
    - /  # corresponds to BTi/4D data
    - .ds/
    - .json
    - .fif
    - .sqd
    - .con
    - .raw
    - .ave
    - .mrk
    - .kdf
    - .mhd
  entities:
    subject: required
    session: optional
    task: required
    acquisition: optional
    run: optional
    processing: optional
    split: optional

# Second group
- suffixes:
    - meg
  extensions:
    - .dat
  entities:
    subject: required
    session: optional
    acquisition: # note that this introduces in the schema the possibility to declare "reserved values"
      requirement: required 
      type: string
      enum:
        - calibration

# Third group
- suffixes:
    - meg
  extensions:
    - .fif
  entities:
    subject: required
    session: optional
    task: required
    acquisition: optional
    run: optional
    processing: optional
    split: optional

# Fourth group
- suffixes:
    - meg
  extensions:
    - .fif
  entities:
    subject: required
    session: optional
    acquisition: 
      requirement: required 
      type: string
      enum:
        - crosstalk
```
