### ISSUE TITLE
Define valid value formats in schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#832]
I'm thinking it might also be a good idea to create a new `formats.yaml` that defines the different formats used in the schema. Something like:

```yaml
label:
    description: |
        Freeform labels without special characters.
    pattern: ^[0-9a-zA-Z]+$
index:
    description: |
        Non-negative, non-zero integers, optionally prefixed with leading zeros for sortability.
    pattern: ^[0-9]+$
unit:
    description: |
        A unit.
    pattern: ^[0-9a-zA-Z]+$
```

Unfortunately, I don't actually know how most of those patterns would look. Units, for example, can be freeform text if necessary, but optimally they should be valid combinations of the values in the Units appendix. Plus we have relative paths of multiple flavors, along with URIs. I think `uri`, at least, is offloaded to JSON Schema in the validator.

_Originally posted by @tsalo in https://github.com/bids-standard/bids-specification/issues/792#issuecomment-831462364_

EDIT: Labeling the different types of paths, and thus defining patterns for them, will have to wait until after #820 is resolved, at least.
