### ISSUE TITLE
Use a coherent schema definition syntax

### ISSUE THREAD

**Issue by erdalkaraca** [bids-standard/bids-specification#884]
Currently, the schema consists of a mix of ad-hoc definitions and syntax.
This makes it hard to implement a tool to generically validate a given BIDS dataset.

In the ancpbids project (see below for link) we experimented with various schema definition languages, such as:
- XSD (XML Schema Definition): industry standard with mature support in many programming languages
- YAMALE: a community effort to formalize data structures using YAML format

Since the BIDS community is more comfortable with JSON/YAML formats, I would like to propose using a more formal schema definition language such as YAMALE to map the BIDS specification onto a machine readable schema.

Examples to follow as additional comments...

Links:
ancpbids: https://github.com/ANCPLabOldenburg/ancp-bids
XSD: https://www.w3.org/TR/xmlschema11-1/
Yamale: https://github.com/23andMe/Yamale

**Comment by erdalkaraca** [comment]
An example of how a coherent schema might look like using Yamale:

```yaml
Dataset:
  .extends: Folder
  subjects: list(include('Subject'), required=False)
  dataset_description: include('DatasetDescriptionFile')
  README: include('File', required=False)
  CHANGES: include('File', required=False)
  LICENSE: include('File', required=False)
  genetic_info: include('JsonFile', required=False)
  samples: include('JsonFile', required=False)
  participants_tsv: include('ParticipantsTsvFile', required=False)
  participants_json: include('TsvSidecarFile', required=False)
  code: include('Folder', required=False)
  derivatives: include('DerivativeFolder', required=False)
  sourcedata: include('Folder', required=False)
  stimuli: include('Folder', required=False)

---
JSONSchemaType:
  map()

MetadataFieldDefinition:
  name: str()
  description: str()
  type: include('JSONSchemaType')

SuffixDefinition:
  name: str()
  description: str()
  type: include('JSONSchemaType')

EntitiyDefinition:
  key: str()
  name: str()
  entity: str()
  description: str()
  type: include('JSONSchemaType')
```

**Comment by erdalkaraca** [comment]
Example definitions of entities:

```yaml
- key: subject
  name: Subject
  entity: sub
  description: |
    A person or animal participating in the study.
  type: label
- key: run
  name: Run
  entity: run
  description: |
    If several scans with [...]
  type: index
- key: mtransfer
  name: Magnetization Transfer
  entity: mt
  description: |
    If files belonging [...]
  type:
    enum:
      - "on"
      - "off"
- key: part
  name: Part
  entity: part
  description: |
    This entity is used to [...]
  type:
    enum:
      - mag
      - phase
      - real
      - imag
```

**Comment by erdalkaraca** [comment]
Example metadata fields definitiones:

```yaml
- name: AcquisitionDuration
  description: |
    Duration (in seconds) of [...]
  type:
    min: 0
    unit: s

- name: AnatomicalLandmarkCoordinates
  description: |
    Key:value pairs of any [...]
    example: `{"AC": [127,119,149], "PC": [128,93,141],
    "IH": [131,114,206]}`, or `{"NAS": [127,213,139], "LPA": [52,113,96],
    "RPA": [202,113,91]}`
  type:
    patternProperties:
      "^[A-Z]{2}$":
        type: array
          items:
            type: number
          minItems: 3
          maxItems: 3
```
