### ISSUE TITLE
Support full object definitions for valid values in schema

### ISSUE THREAD

**Issue by tsalo** [bids-standard/bids-specification#904]
Currently, valid values (i.e., `enum`s) for objects in the schema are written as lists. However, in some cases, we also want to have each value defined, and perhaps even summarized in a separate table. As an example, take the [channels file for MEG data](https://bids-specification.readthedocs.io/en/latest/04-modality-specific-files/02-magnetoencephalography.html#channels-description-_channelstsv). Each of the valid values for the `type` column has a description, which is currently rendered  with a hardcoded table, but which could be incorporated into the schema directly.

**Comment by tsalo** [comment]
As an example, here's this idea applied to the "volume_type" column for ASL context files:

```yaml
volume_type:
  name: volume_type
  description: |
    The `*_aslcontext.tsv` table consists of a single column of labels identifying
    the `volume_type` of each volume in the corresponding `*_asl.nii[.gz]` file.
  type: string
  enum:
  - control:
      name: Control Image
      description: |
        The control image is acquired in the exact same way as the label image,
        except that the magnetization of the blood flowing into the imaging region has not been inverted.
  - label:
      name: Label Image
      description: |
        The label image is acquired in the exact same way as the control image,
        except that the blood magnetization flowing into the imaging region has been inverted.
  - m0scan:
      name: M0 Image
      description: |
        The M0 image is a calibration image, used to estimate the equilibrium magnetization of blood.
  - deltam:
      name: deltaM Image
      description: |
        The deltaM image is a perfusion-weighted image, obtained by the subtraction of `control` - `label`.
  - cbf:
      name: Cerebral Blood Flow Image
      description: |
        The cerebral blood flow (CBF) image is produced by dividing the deltaM by the M0,
        quantified into `mL/100g/min` (See also [doi:10.1002/mrm.25197](https://doi.org/10.1002/mrm.25197))
```
