### ISSUE TITLE
Use pre-commit to lint files upon commit

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-specification#928]
Can we please add the following pre-commit config to the repo: I am getting tired of CI telling I have commited wrongly formatted yml or files with trailing white space.

```
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
```
